### ISSUE TITLE
Complete the assessment and documentation for the Astrorapid ZTF test

### ISSUE THREAD

**Issue by smarttgit** [lsst-uk/lasair#102]

**Comment by tms-epcc** [comment]
Michael to add a link to the documentation and then ticket can be closed

**Comment by mFulton07** [comment]
Here is the review from Jan 2020. RAPID has gone through upgrades since then, but the most recent version seems to be broken - the classifications are producing a mystery transient (see https://github.com/daniel-muthukrishna/astrorapid/issues/7). 

[RAPID_First_Impressions (1).pdf](https://github.com/lsst-uk/lasair/files/5841909/RAPID_First_Impressions.1.pdf)
