### ISSUE TITLE
API testing

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#159]
Invite some users to try the API
Build sample Jupyter notebooks that use the API

**Comment by thespacedoctor** [comment]
I have been testing the API for ~10 minute but have hit the `{"detail":"Request was throttled. Expected available in 3169 seconds."}` warning. Maybe someone else is also testing with the dummy API authentication token at the same time. What is the current throttle limit?

Good to see the throttle limit is working!

**Comment by RoyWilliams** [comment]
Glad to see the throttling is working. And glad to see that you recognize what is happening.
https://www.django-rest-framework.org/api-guide/throttling/#userratethrottle

 I have it set really stingy now
-- Every user has a limit of 10 per hour. 
-- Queries are limited to 10,000 records and 50 minutes
-- Queries from the 'dummy' user are limited to 1,000 records and 5 minutes

What should I set these to?

**Comment by RoyWilliams** [comment]
I made it 100/day per user.

**Comment by thespacedoctor** [comment]
Throttle limit time window could be time-bound rather than API call count bound. So instead of N-API calls per hour it could be 1 API call per N-sec. This would help spread the load of API calls and make them less 'bursty' every time a user is assigned a new batch of N-API calls.

100/day is very limiting.

Can I suggest 1 API call per second & 10,000 records per minute?

**Comment by RoyWilliams** [comment]
Can't do per second. 
I changed it to  'user': ['30/minute', '1000/day']
Howzat?

**Comment by thespacedoctor** [comment]
We can work with that for now 👍

**Comment by thespacedoctor** [comment]
I'm impressed with the API so far, and it's clear just how powerful this feature will be.

`/api/cone`

Bugs:

- This should be a 'GET' request but is assigned as 'POST' 

Requests:

- The ability to pass the authentication token and data via URL parameters instead of HEADER and BODY would be extremely useful as then users can save links to common API calls and test in browser. As long as there is an SSL certificate (which there is currently) all data in the URL apart from the domain name is encrypted so there is no security threat to this option.

`/api/query`

Bugs:

- Again this should be a 'GET' request but is assigned as 'POST' 

Requests:

- Pagination for results would allow to remove the 10,000 record limit. For example, if we had a 1000 record page limit and a user enters a query which returns 7,081 results, the use would require 8 API calls to paginate and collect all the results. This is a nice way of throttling traffic without limiting the user's ability to collect all the data she wants.
- Move away from the SQL nature of requests to a few well documented api resources like `/api/objects/`, `/api/watchlists/`, `/api/crossmatches/`,  `/api/candidates/` etc that can be filtered by defined parameters. Once these resources are fleshed out then the possibilities for scripting and building third-party products off the back of Lasair are huge.
