### ISSUE TITLE
Announce to beta tester list

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#228]
Simple email to beta testers page?

**Comment by tms-epcc** [comment]
@andyxerxes emailed beta users on 23/APR/21

---

SHORT VERSION
* Please do try out the development version of Lasair
* Send us any useful comments and suggestions

==Lasair development version release===

The public version of the Lasair event broker, processing ZTF alerts, is at https://lasair.roe.ac.uk . The last official release was in April 2020 (Lasair 2.0). As you will know, we have made relatively few changes to this stable operating facility, because in the background we have been working on a new version of Lasair intended for use with the Rubin Observatory, and its LSST survey. We are halfway through our project to build the new Rubin-version. Our development version is certainly not ready for public use, but we would like to make it available for testing and comment by selected beta-testers. The development version is here:

https://lasair-iris.roe.ac.uk

We would welcome informal feedback and suggestions, which you can do as explained on the contact page, either by email or on Github:

https://lasair-iris.roe.ac.uk/contact

Please remember that it is not expected yet to be flawless, or totally reliable, or cosmetically perfect. (We know for example that there is some inconsistent behaviour depending on browser - we are working on this.) But it does give a good idea of the core functionality. We have made considerable changes in the back-end technology and deployment, but don't expect you to notice these or comment on them. Rather, we would like to point out some key changes from the user point of view:

* The web pages, and associated functionality, have been re-organised
* The pre-cooked tables choice in "make a query" has changed
* As well as watchlists of sources, you can run queries against
an area defined by a MOC
* Table schemas are more visible
* In the object page listing "candidates" every image is now examinable using a simple FITS viewer
* Scripted acccess is still via Jupyter notebooks, but now has an API, so notebooks can be run from your own machine
* The example notebooks provided are hosted on Google Colab

Have fun, and we look forward to any comments you have

Andy, Roy, Stephen
