### ISSUE TITLE
Review and improve offering on LIGO-Virgo and Fermi-GBM skymaps

### ISSUE THREAD

**Issue by smarttgit** [lsst-uk/lasair#56]
We are nearly there in making this scientifically useful, but could do with a few enhancements. At present nobody uses it as it not scientifically functional, but with some effort this could be a good feature for V2.0 release 

https://lsst-uk.atlassian.net/wiki/spaces/LUSCSWG/pages/128516170/UK+Science+requirements+for+the+transient+server+Lasair+for+Level+1+Alerts

This thread will document what we want

**Comment by smarttgit** [comment]
https://lasair.roe.ac.uk/skymap/

This is a useful compilation list. Could we make it into a a table instead, with the rows being the events (as listed) and each of them having 5 columns. With the info propagated from the information on each of the objects pages. We have this info and we display it, we just need to put in this top table. 

Distance 
ISO Date:
Julian date
Percent probability
max prob RA,Dec 

This will give uses a rapid overview 

Note that we need to include "Terrestrial" probability. For some reason that is not displaying

**Comment by smarttgit** [comment]
Need a button to download an ascii file of the Glade galaxies contained within the 90% contour. Can it return the following : Name, RA, DEC, redshift or distance , angular size, magnitude, absolute magnitude, and the probability contour within which the galaxy lies. 

Note that the last value is NOT the probability in the healpix pixel at that position. Since that will be close to zero for all. It is with the contour within which the galaxy falls. 

Note that Dave has code for this if you need it

**Comment by smarttgit** [comment]
Can you add another Mollweide projection (done with Aitoff), with RA and DEC grid lines (degrees please!)

And the clickable ZTF coverage should be boxes the size of the camera - not the size of the number of transients in the field. Currently it is pretty but not useful

**Comment by smarttgit** [comment]
The tool to add the ZTF transients that are -X to +Y days from trigger is very useful. And nice to see them pop up.  But it must be changed to OBJECTS, not candidates 

Currently it selects any candidate with any detection in that time window - which is not useful. 
We need to select only OBJECTS which have their FIRST detection within that time window. 

And as well as the plot, we need to return a table of these OBJECTS 

We either need to remove the Sherlock classified stars VS and AGN or give buttons to say
"remove VS objects"  and/or  "remove AGN" 

In the Table, give the probability contour within which they are contained, and Sherlock redshift (that helps to filter the objects by likelihood).

**Comment by smarttgit** [comment]
Is it possible  to add functionality to plot specific points on the sky map? E.g. by providing a list of coordinates via text upload. Would be very useful for plotting specific known candidates – especially since the candidates produced by ZTF are not released as public alerts.

**Comment by smarttgit** [comment]
Stephen to write to ZTF to see if we can get an LSST dry-run type of trigger. They will not do this for NSBH or BNS events, but may do it for us a BBH. 

For example, ZTF trigger their public telescope time on a BBH and tile out the region, we test how fast we can get the objects into Lasair and make all of the above functionality work. The top level quesiton is how fast can a user access objects once a GW event has had the telescope triggered. I think ZTF might do this for us as a test, with a BBH.

**Comment by RoyWilliams** [comment]
(1) Many GLADE galaxies do not have redshift, but this seems to be an essential component. Should we just ignore all those, so that every galaxy has a redshift? If not, how do we effectively marginalise over redshift?

(2) Which ZTF transients to show?
-- objects not candidates
-- objects with jdmin from -X to +Y relative to the event
-- sherlock join with no VS, BS, AGN

(3) Terrestrial probability. The LIGO people keep adding more classifications. I can add this one easily.

(4) Coverage map. I can add a box for each field showing its real size.

(7) The probability that I listed on the web page is relative to the sum of the probabilities of all the other GLADE galaxies. Foe each one, we compute the 3D skymap probability, then normalise by the sum of all of these. Foe example https://lasair.roe.ac.uk/skymap/GW170817/ shows the correct galaxy (NGC 4993) with probability of 9.11%.

(8) (a) We already have Aitoff projection. But the contour lines wrap round sometimes and it looks bad with horizontal lines (ask Ken). (b) I have asked Thomas Boch about making a RA/Dec grid on the Aladinlite and have not received and answer.

(9) We can make a table of possible ZTF transients, but what is the sort order? How to find the most likely ZTF transient? The one with the highest 3d skymap probability, like the galaxy list?

**Comment by mnicholl** [comment]
Agree with all Stephen's suggestions. To me, the most useful version of this page would have two tables right below the sky map. Both should have download buttons.

1. Objects table (ONLY for objects with jdmin > LIGO alert), ranked by probability.
At least the following columns:
ZTF name | First detection (Days post-trigger) | most recent detection | peak g | peak r | absolute mag* | g-r colour** | Sherlock host name | probability***

* For the absolute mag, use the LIGO distance at that healpix position. Could use brighter of g/r, or both
** Not sure how best to define the colour... could use gmean - rmean, or only calculate if a detection on same day
*** Either the X% contour, or probably better to use the probability for the Sherlock host, if available.

2. GLADE table, as Stephen suggested. I would also add a column for associated ZTF objects.

I think the best version of the probability ranking calculation takes into account the galaxy mass (luminosity). Basically an algorithm like this: https://github.com/Lanasalmon/HOGWARTs

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @andyxerxes has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2352578725/A3.09+Report) for the A3.09 activity. At the above meeting it was agreed to close all tickets in the A3.09 current activity.
