### ISSUE TITLE
Write Sherlock documentation

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#66]
Aimed at the user. Integration into Lasair website in separate card.

**Comment by smarttgit** [comment]
What this specifically means for now is 

Create a tab on the left hand bar on https://lasair.roe.ac.uk/ called "Sherlock"

Link this to a new page with the following text. 

Sherlock is a software package and integrated massive database system that provides a rapid and 
reliable spatial cross-match service for any astrophysical variable or transient. The concept originated in the PhD thesis of D. Young at QUB, and has been developed by Young et al. in many iterations and cycles since. It associates the position of a transient with all major astronomical catalogues and assigns a basic classification to the transient. At its most basic, it separates stars, AGN and supernova-like transients. It has been tested within QUB on a daily basis with ATLAS and Pan-STARRS transients, and within PESSTO as part of the PESSTO marshall system that allows prioritising of targets.   It is thus a boosted decision tree algorithm. A full paper describing the code, catalogues and algorithms is in preparation (Young et al. in prep). A summary is included in Section 4.2 of "Design and Operation of the ATLAS Transient Science Server"  (Smith, Smartt, Young et al. 2020, submitted to PASP : https://arxiv.org/abs/2003.09052).  
That section is copied here and users should currently cite that paper (Smith et al. 2020) for Sherlock use : 

Relevant part of Section 4.2 of Smith et al  (paraphrased in some cases)  : 

Sherlock: Once an object .....  _Ken - copy in the text here from the paper. You may have to adjust and remove references to Tables/Figures etc_

**Comment by genghisken** [comment]
Actually I've made good progress with the overleaf conversion of the STANDALONE Sherlock document into HTML  I need to merge it with the text above.  When I've got it ready I'll need Roy to put it in the right place, since the Lasair web code is currently deployed under his account.

**Comment by genghisken** [comment]
The HTML is now written and I've committed the changes to Lasair.  Roy just needs to do a git pull and restart the webserver.  I can't see if there are issues until the updated web pages (and image) are deployed!

**Comment by RoyWilliams** [comment]
Its now in github, lasair, and lasair-dev. I also replaced several links in /schema and /about from readthedocs to /sherlock. Can you check if it all looks OK?

**Comment by genghisken** [comment]
Looks fine!  Thanks Roy!  There's at least one more link to the readthedocs pages on the Filters & Queries page...

**Comment by smarttgit** [comment]
Could we make this bold  font: 

That section is copied here and users should currently cite that paper (Smith et al. 2020) for Sherlock use:

And also add the link to https://arxiv.org/abs/2003.09052 in the sentence.

Otherwise, this is closed and done.

**Comment by genghisken** [comment]
Changes made and checked in.  Roy - feel free to do another git pull on both the lasair and lasair-dev webservers.  You do NOT need to restart the webserver.  (It's just a template change.)

**Comment by RoyWilliams** [comment]
done

**Comment by genghisken** [comment]
Can you roll it out to live as well!  (I can see it on lasair-dev OK.)

**Comment by andyxerxes** [comment]
as matter of principle we should not roll it to live until we have done our “readiness review” tomorrow

  andy

------------------------------------------------------------
Andy Lawrence : Regius Professor of Astronomy, University of Edinburgh
Institute for Astronomy,  Royal Observatory, Blackford Hill, Edinburgh, EH9 3HJ
Email al@roe.ac.uk   /  Phone +44-(0)131-668-8346  / Skype andyxlawrence
-----------------------------------------------------------
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.


On 7 Apr 2020, at 14:31, genghisken <notifications@github.com> wrote:


Can you roll it out to live as well! (I can see it on lasair-dev OK.)

**Comment by genghisken** [comment]
OK

**Comment by genghisken** [comment]
I've changed the "Sherlock" link to "Classification and Annotation" and added a couple of sentences at the beginning of the Sherlock page, which is now also headed "Classification and Annotation."  Roy - can you do a git pull on lasair-dev?  Everyone else - feel free to comment and I'll integrate any further changes.
