### ISSUE TITLE
Deployment of big database

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#97]
Define and implement ways to port the 5 TB Sherlock database from one machine to another

**Comment by genghisken** [comment]
This is the second part of the Ansible deployment.  (The first part is to install & configure MySQL. Separate task.)  The database files have been cloned to a "staging area" on CephFS.  Next stage is to use Ansible to:

* Create a new Sherlock database
* Run the create table script
* Drop the InnoDB Tablespaces
* Copy the staged files in place
* Reattach the InnoDB Tablespaces

All ready to go, but alas, we are blocked once more, since OpenStack network is misbehaving.  I may be able to demo a small  InnoDB table install (i.e. a subset of Sherlock) to an existing tiny instance while we wait for network fixes.  (Probably best to test like this anyway.)

**Comment by genghisken** [comment]
OpenStack network is now fixed for the time being.  Moving back to in progress.

**Comment by genghisken** [comment]
A generic Sherlock deployment script has been completed and is currently being tested.

**Comment by tms-epcc** [comment]
30JUN/21
- Roy and TerryS agreed this can be closed
